name: SM-A042F Kernel Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          path: kernel/source
          fetch-depth: 1

      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: ./kernel/source/
          config: a04e_defconfig
          arch: arm64
          aosp-clang: true
          aosp-gcc: true
          android-version: 12
          aosp-clang-version: r383902
          extra-make-args: LLVM=1
